/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlege.view.frontier;

import javax.swing.JOptionPane;
import ru.exlege.model.bean.Eleitor;
import ru.exlege.model.dao.EleitorDao;
import ru.exlege.model.dao.VotoDao;
import ru.exlege.model.pojo.PNLVotacaoChildren;

/**
 *
 * @author dmitry
 */
public class PNLInsertDataWindow extends PNLVotacaoChildren {

    /**
     * Creates new form PNLInsertDataWindow
     *
     * @param calling
     */
    public PNLInsertDataWindow(WNDVotacao calling) {
        super(calling);
        initComponents();
        setMainComponent(jTtitulo);
        jTtitulo.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTtitulo = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem vindo!");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Insira o número do seu título para votar");

        jTtitulo.setForeground(new java.awt.Color(12, 105, 157));
        try {
            jTtitulo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTtitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTtitulo.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jTtitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtituloMouseClicked(evt);
            }
        });
        jTtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtituloActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(4, 78, 1));
        jButton1.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Iniciar Votação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTtitulo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtituloActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_jTtituloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Eleitor eleitor = EleitorDao.consultar(Long.parseLong(jTtitulo.getText().replace(" ", "")));
        if (eleitor != null) {
            if (VotoDao.verifyAble(eleitor.getTitulo())) {
                getCaller().addContent(new PNLVotacao(getCaller(), eleitor));
            } else {
                JOptionPane.showMessageDialog(null, "Ops, parece que você já votou.\nSe você não votou e está vendo essa mensagem, consulte o administrador do sistema.", "Erro", JOptionPane.ERROR_MESSAGE);
                jTtitulo.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum eleitor relacionado à esse título foi encontrado \nVerifique suas informações, caso o problema persista consulte o administrador do sistema.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTtituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtituloMouseClicked
        jTtitulo.requestFocus();
        jTtitulo.grabFocus();
    }//GEN-LAST:event_jTtituloMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField jTtitulo;
    // End of variables declaration//GEN-END:variables
}
