/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlege.view.frontier;

import java.awt.Color;
import ru.exlege.model.pojo.ConnectionFactory;
import ru.exlege.model.pojo.JView;

/**
 *
 * @author dmitry
 */
public class PNLLoginFrame extends JView {

    /**
     * Creates new form PNLLoginFrame
     *
     * @param parent
     */
    public PNLLoginFrame(WNDMainWindow parent) {
        super(parent, true);
        initComponents();
        jLbErrorLb.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTpassword = new javax.swing.JPasswordField();
        jBcancel = new javax.swing.JButton();
        jBlogin = new javax.swing.JButton();
        jLbErrorLb = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 10, true));
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jTid.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTid.setNextFocusableComponent(jTpassword);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD");

        jTpassword.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTpassword.setNextFocusableComponent(jBlogin);

        jBcancel.setBackground(new java.awt.Color(151, 2, 36));
        jBcancel.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jBcancel.setForeground(new java.awt.Color(254, 254, 254));
        jBcancel.setText("Cancelar");
        jBcancel.setNextFocusableComponent(jTid);
        jBcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelActionPerformed(evt);
            }
        });

        jBlogin.setBackground(new java.awt.Color(1, 119, 13));
        jBlogin.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jBlogin.setForeground(new java.awt.Color(254, 254, 254));
        jBlogin.setText("Login");
        jBlogin.setNextFocusableComponent(jBcancel);
        jBlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBloginActionPerformed(evt);
            }
        });

        jLbErrorLb.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLbErrorLb.setForeground(new java.awt.Color(152, 1, 11));
        jLbErrorLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbErrorLb.setText("Incorrect ID or PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTid)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTpassword)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBcancel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLbErrorLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbErrorLb, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancel)
                    .addComponent(jBlogin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBloginActionPerformed
        performAction("LOGIN@PNLLoginFrame", new Object[]{ConnectionFactory.testConnection(jTid.getText(), new String(jTpassword.getPassword()))});
    }//GEN-LAST:event_jBloginActionPerformed

    private void jBcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelActionPerformed
        performAction("CANCEL@PNLLoginFrame", null);
    }//GEN-LAST:event_jBcancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancel;
    private javax.swing.JButton jBlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLbErrorLb;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTid;
    public javax.swing.JPasswordField jTpassword;
    // End of variables declaration//GEN-END:variables
}
