/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlege.view.frontier;

import java.applet.Applet;
import java.applet.AudioClip;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ru.exlege.model.bean.Candidato;
import ru.exlege.model.bean.Eleitor;
import ru.exlege.model.dao.CandidatoDao;
import ru.exlege.model.dao.VotoDao;
import ru.exlege.model.pojo.PNLVotacaoChildren;

/**
 *
 * @author dmitry
 */
public class PNLVotacao extends PNLVotacaoChildren {

    /**
     * Creates new form PNLVotacao
     */
    private final Eleitor eleitor;
    private Candidato current;

    DefaultListModel<Candidato> listModel;

    public PNLVotacao(WNDVotacao calling, Eleitor eleitorCall) {
        super(calling);
        initComponents();
        jLcandidatos.setModel(new DefaultListModel<>());
        listModel = (DefaultListModel) jLcandidatos.getModel();

        generateWhite();
        generateNull();

        for (Candidato can : getCaller().getCandidatos()) {
            listModel.addElement(can);
        }

        this.eleitor = eleitorCall;
        String nomePaths[] = eleitorCall.getNome().split(" ");
        String newName = nomePaths.length > 2 ? nomePaths[0] + " " + nomePaths[1] : nomePaths[0];
        jTbemvindo.setText(jTbemvindo.getText().replace("<$>", newName));
        jTtitulo.setText(jTtitulo.getText().replace("<$>", String.valueOf(eleitor.getTitulo())));
        jTnascimento.setText(jTnascimento.getText().replace("<$>", eleitor.getNascimento()));
    }

    private void generateWhite() {
        Candidato branco = CandidatoDao.getWhite();
        if (branco != null) {
            Candidato existente = new Candidato(branco.getPid()) {
                @Override
                public String toString() {
                    return "VOTO EM BRANCO";
                }
            };
            existente.setNome("VOTO EM BRANCO");
            existente.setPartido("");
            listModel.addElement(existente);
        }
    }

    private void generateNull() {
        Candidato nulo = new Candidato(0) {
            @Override
            public String toString() {
                return "VOTO NULO";
            }
        };
        nulo.setNome("VOTO NULO");
        nulo.setPartido("");
        listModel.addElement(nulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTbemvindo = new javax.swing.JLabel();
        jTtitulo = new javax.swing.JLabel();
        jTnascimento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLcandidatos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTnome = new javax.swing.JLabel();
        jTpartido = new javax.swing.JLabel();
        jPfoto = new javax.swing.JPanel();
        jTimagem = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTcodigo = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTbemvindo.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jTbemvindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTbemvindo.setText("Bem vindo(a), <$>!");

        jTtitulo.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTtitulo.setText("Seu título eleitoral : <$>");

        jTnascimento.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTnascimento.setText("Data de Nascimento : <$>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTbemvindo, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTtitulo)
                            .addComponent(jTnascimento))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTbemvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnascimento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLcandidatos.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLcandidatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLcandidatos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLcandidatosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLcandidatos);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 30, 70));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Candidatos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTnome.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTnome.setForeground(new java.awt.Color(255, 0, 37));
        jTnome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTnome.setText(" ");

        jTpartido.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTpartido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTpartido.setText(" ");

        jPfoto.setBackground(new java.awt.Color(254, 254, 254));
        jPfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTimagem.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTimagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTimagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTimagem.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPfotoLayout = new javax.swing.GroupLayout(jPfoto);
        jPfoto.setLayout(jPfotoLayout);
        jPfotoLayout.setHorizontalGroup(
            jPfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTimagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPfotoLayout.setVerticalGroup(
            jPfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTimagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(11, 106, 2));
        jButton1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTcodigo.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTcodigo.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTpartido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTnome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPfoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTpartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTcodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLcandidatosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLcandidatosValueChanged
        jButton1.setEnabled(true);
        jTimagem.setText("");
        jTimagem.setIcon(null);
        current = listModel.getElementAt(jLcandidatos.getSelectedIndex());
        jTnome.setText(current.getNome());
        if (!current.getNome().equals("VOTO EM BRANCO") && current.getPid() != 0) {
            jTpartido.setText(current.getPartido());
            jTcodigo.setText(String.valueOf(current.getPid()));
            jPfoto.setVisible(true);
        } else {
            jTpartido.setText("");
            jTcodigo.setText("");
            jPfoto.setVisible(false);
        }

        if (current.getFoto() != null) {
            jTimagem.setText("");
            try {
                jTimagem.setIcon(new ImageIcon(ImageIO.read(current.getFoto().getBinaryStream())));
            } catch (SQLException | IOException ex) {
                Logger.getLogger(PNLVotacao.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            jTimagem.setText("SEM FOTO");
        }

    }//GEN-LAST:event_jLcandidatosValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (current != null) {
            int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja consumar seu voto?", "Voto", JOptionPane.INFORMATION_MESSAGE);
            if (confirmacao == JOptionPane.OK_OPTION) {
                if (VotoDao.commitVote(eleitor.getTitulo(), current.getPid(), current.getNome().equals("VOTO EM BRANCO"))) {
                    getCaller().addContent(new PNLEnding(getCaller()));
                } else {
                    JOptionPane.showMessageDialog(null, "Um erro ocorreu\nConsulte o administrador do sistema", "Erro", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um candidato, voto nulo ou voto em branco", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jLcandidatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPfoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTbemvindo;
    private javax.swing.JLabel jTcodigo;
    private javax.swing.JLabel jTimagem;
    private javax.swing.JLabel jTnascimento;
    private javax.swing.JLabel jTnome;
    private javax.swing.JLabel jTpartido;
    private javax.swing.JLabel jTtitulo;
    // End of variables declaration//GEN-END:variables
}
