/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlege.view.frontier;

import ru.exlege.view.frontier.internal.IFInsertElector;
import ru.exlege.view.frontier.internal.IFEditElector;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;

/**
 *
 * @author dmitry
 */
public class WNDElectorKeep extends javax.swing.JFrame {

    /**
     * Creates new form WNDElectorKeep
     */
    private final JButton jBcad;
    
    private final JButton jBpes;
    
    public WNDElectorKeep() {
        initComponents();
        
        jBcad = new JButton();
        jBcad.setText("Cadastro [+]");
        jBcad.setFocusable(false);
        
        jBcad.addActionListener((ActionEvent e) -> {
            IFInsertElector insertElector = new IFInsertElector();
            insertElector.setVisible(true);
            insertElector.setLocation(this.getWidth() / 2 - insertElector.getWidth() / 2,
                    this.getHeight() / 2 - insertElector.getHeight() / 2);
            jDPMainPanel.add(insertElector);
            try {
                insertElector.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(WNDElectorKeep.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        jBpes = new JButton();
        jBpes.setText("Pesquisa [+]");
        jBpes.setFocusable(false);
        
        jBpes.addActionListener((ActionEvent e) -> {
            IFEditElector editElector = new IFEditElector();
            editElector.setVisible(true);
            editElector.setLocation(this.getWidth() / 2 - editElector.getWidth() / 2,
                    this.getHeight() / 2 - editElector.getHeight() / 2);
            jDPMainPanel.add(editElector);
            try {
                editElector.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(WNDElectorKeep.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        jMenuBar1.add(jBcad);
        jMenuBar1.add(jBpes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPMainPanel = new JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(new ImageIcon(getClass().getResource("/ru/exlege/view/gfx/bgenvironment_1.png")).getImage(), 0, 0, this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EX LEGE : Eleitores");
        setResizable(false);

        jDPMainPanel.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WNDElectorKeep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WNDElectorKeep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WNDElectorKeep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WNDElectorKeep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WNDElectorKeep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPMainPanel;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
