/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlege.view.frontier;

import javax.swing.DefaultListModel;
import ru.exlege.model.bean.AveragePair;
import ru.exlege.model.dao.VotoDao;
import ru.exlege.model.pojo.Analytics;

/**
 *
 * @author dmitry
 */
public class WNDEstatisticas extends javax.swing.JFrame {

    /**
     * Creates new form WNDEstatisticas
     */
    private Analytics analytics;

    DefaultListModel<AveragePair> model;

    public WNDEstatisticas() {
        initComponents();
        jPurnas.setLayout(null);

        model = (DefaultListModel) jList1.getModel();
        analytics = VotoDao.getAnalytcs();
        int count = 0;
        float seizure;
        for (AveragePair pairs : analytics.getPair()) {
            count++;
            seizure = ((float) pairs.getVotes() / (float) analytics.getTotal());
            model.addElement(pairs);
            switch (count) {
                case 1:
                    jPporFirst.setText(String.valueOf(seizure * 100) + "%");
                    jPfirst.setSize(jPfirst.getWidth(), (int) (jPfirst.getHeight() * seizure));
                    jTnameFirst.setText(pairs.getResumeName());
                    jPfirst.setPreferredSize(jPfirst.getSize());
                    if (pairs.getVotes() <= 0) {
                        jPfirst.setVisible(false);
                        jTnameFirst.setVisible(false);
                    }
                    break;
                case 2:
                    jPporSecond.setText(String.valueOf(seizure * 100) + "%");
                    jTnameSecond.setText(pairs.getResumeName());
                    jPsecond.setSize(jPsecond.getWidth(), (int) (jPsecond.getHeight() * seizure));
                    jPsecond.setPreferredSize(jPsecond.getSize());
                    if (pairs.getVotes() <= 0) {
                        jPsecond.setVisible(false);
                        jTnameSecond.setVisible(false);
                    }
                    break;
                case 3:
                    jPporThird.setText(String.valueOf(seizure * 100) + "%");
                    jTnameThird.setText(pairs.getResumeName());
                    jPthird.setSize(jPthird.getWidth(), (int) (jPthird.getHeight() * seizure));
                    jPthird.setPreferredSize(jPthird.getSize());
                    if (pairs.getVotes() <= 0) {
                        jPthird.setVisible(false);
                        jTnameThird.setVisible(false);
                    }
                    break;
                default:
                    break;
            }
            this.revalidate();
        }

        switch (analytics.getPair().size()) {
            case 1:
                jPsecond.setVisible(false);
                jTnameSecond.setVisible(false);
                jPthird.setVisible(false);
                jTnameThird.setVisible(false);
                break;
            case 2:
                jPsecond.setVisible(false);
                jTnameSecond.setVisible(false);
                break;
            case 3:
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPurnas = new javax.swing.JPanel();
        jPfirst = new javax.swing.JPanel();
        jPporFirst = new javax.swing.JLabel();
        jTnameSecond = new javax.swing.JLabel();
        jTnameFirst = new javax.swing.JLabel();
        jTnameThird = new javax.swing.JLabel();
        jPthird = new javax.swing.JPanel();
        jPporThird = new javax.swing.JLabel();
        jPsecond = new javax.swing.JPanel();
        jPporSecond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPanel2.setBackground(new java.awt.Color(0, 78, 157));
        jPanel2.setPreferredSize(new java.awt.Dimension(590, 40));

        jLabel1.setBackground(new java.awt.Color(139, 1, 13));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Estatísticas da votação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        jPurnas.setOpaque(false);
        jPurnas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPfirst.setBackground(new java.awt.Color(18, 136, 253));
        jPfirst.setPreferredSize(new java.awt.Dimension(68, 300));

        jPporFirst.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jPporFirst.setForeground(new java.awt.Color(254, 254, 254));
        jPporFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPporFirst.setText("100%");

        javax.swing.GroupLayout jPfirstLayout = new javax.swing.GroupLayout(jPfirst);
        jPfirst.setLayout(jPfirstLayout);
        jPfirstLayout.setHorizontalGroup(
            jPfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfirstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPporFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPfirstLayout.setVerticalGroup(
            jPfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfirstLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPporFirst)
                .addContainerGap())
        );

        jPurnas.add(jPfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 120, 306));

        jTnameSecond.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jTnameSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTnameSecond.setText("jLabel2");
        jTnameSecond.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTnameSecond.setPreferredSize(new java.awt.Dimension(100, 20));
        jPurnas.add(jTnameSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 12, 120, -1));

        jTnameFirst.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jTnameFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTnameFirst.setText("jLabel2");
        jTnameFirst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTnameFirst.setPreferredSize(new java.awt.Dimension(100, 20));
        jPurnas.add(jTnameFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 120, -1));

        jTnameThird.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jTnameThird.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTnameThird.setText("jLabel2");
        jTnameThird.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTnameThird.setPreferredSize(new java.awt.Dimension(100, 20));
        jPurnas.add(jTnameThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 12, 120, -1));

        jPthird.setBackground(new java.awt.Color(174, 208, 2));
        jPthird.setPreferredSize(new java.awt.Dimension(68, 300));

        jPporThird.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jPporThird.setForeground(new java.awt.Color(254, 254, 254));
        jPporThird.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPporThird.setText("100%");

        javax.swing.GroupLayout jPthirdLayout = new javax.swing.GroupLayout(jPthird);
        jPthird.setLayout(jPthirdLayout);
        jPthirdLayout.setHorizontalGroup(
            jPthirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPthirdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPporThird, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPthirdLayout.setVerticalGroup(
            jPthirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPthirdLayout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jPporThird)
                .addContainerGap())
        );

        jPurnas.add(jPthird, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 50, 120, 306));

        jPsecond.setBackground(new java.awt.Color(201, 1, 102));
        jPsecond.setPreferredSize(new java.awt.Dimension(68, 300));

        jPporSecond.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jPporSecond.setForeground(new java.awt.Color(254, 254, 254));
        jPporSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPporSecond.setText("100%");

        javax.swing.GroupLayout jPsecondLayout = new javax.swing.GroupLayout(jPsecond);
        jPsecond.setLayout(jPsecondLayout);
        jPsecondLayout.setHorizontalGroup(
            jPsecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPsecondLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPporSecond, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPsecondLayout.setVerticalGroup(
            jPsecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPsecondLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPporSecond)
                .addContainerGap())
        );

        jPurnas.add(jPsecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, 120, 306));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPurnas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPurnas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WNDEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WNDEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WNDEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WNDEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WNDEstatisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPfirst;
    private javax.swing.JLabel jPporFirst;
    private javax.swing.JLabel jPporSecond;
    private javax.swing.JLabel jPporThird;
    private javax.swing.JPanel jPsecond;
    private javax.swing.JPanel jPthird;
    private javax.swing.JPanel jPurnas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTnameFirst;
    private javax.swing.JLabel jTnameSecond;
    private javax.swing.JLabel jTnameThird;
    // End of variables declaration//GEN-END:variables
}
