/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlege.view.frontier;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ru.exlege.model.dao.PrivilegesDao;
import ru.exlege.model.pojo.ConnectionFactory;
import ru.exlege.model.pojo.FuzzyLabelSet;
import ru.exlege.model.pojo.JView;
import ru.exlege.model.pojo.PasswordUtils;

/**
 *
 * @author dmitry
 */
public class WNDMainWindow extends javax.swing.JFrame {

    /**
     * Creates new form WNDMainWindow
     */
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

    private PNLLoginFrame loginFrame;
    private final FuzzyLabelSet labelSet;
    public static final Color DEEP_BLUE = new Color(14, 56, 98);
    private final Image IMAGEM = new ImageIcon(getClass().getResource("/ru/exlege/view/gfx/logo.png")).getImage();

    public WNDMainWindow() {
        initComponents();
        jContentPanel.setLayout(null);
        System.gc();
        System.runFinalization();
        initLoginFrame();
        verifyConnection();

        labelSet = new FuzzyLabelSet();

        jLbCandidatos.addMouseListener(labelSet);
        jLbEleitores.addMouseListener(labelSet);
        jLbVotacao.addMouseListener(labelSet);
        jLbEstatisticas.addMouseListener(labelSet);
    }

    private synchronized void verifyConnection() {
        new Thread(() -> {
            System.err.println("[EVENT] Windows gained focus.");
            while (this.isFocused()) {
                System.err.println("[EVENT] Verifying connection");
                if (ConnectionFactory.testPeriodicConnection()) {
                    jLbConnection.setIcon(new ImageIcon(this.getClass().getResource("/ru/exlege/view/gfx/connected.png")));
                    jLbConnection.setToolTipText("Connected");
                } else {
                    jLbConnection.setIcon(new ImageIcon(this.getClass().getResource("/ru/exlege/view/gfx/disconnected.png")));
                    jLbConnection.setToolTipText("Disconnected!");
                }
                try {
                    Thread.sleep(6000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(WNDMainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            System.err.println("[EVENT] Windows lost focus.");
        }).start();
    }

    private void initPanel(JView panel) {
        panel.setSize(panel.getPreferredSize());
        panel.setLocation((dim.width / 2) - (panel.getWidth() / 2), (dim.height / 2) - (panel.getHeight() / 2));
        jContentPanel.add(panel);
        panel.setVisible(true);
        panel.repaint();
        this.repaint();
    }

    private void initLoginFrame() {
        loginFrame = new PNLLoginFrame(this);
        loginFrame.setOpaque(false);
        initPanel(loginFrame);
    }

    public void trigger(String str, Object args[]) {
        System.err.println("[EVENT] Trigger " + str + " w/ paramethers " + Arrays.toString(args));
        switch (str) {
            case "LOGIN@PNLLoginFrame":
                if ((boolean) args[0]) {
                    loginFrame.setVisible(false);
                    jLbCandidatos.setEnabled(true);
                    jLbEleitores.setEnabled(true);
                    jLbVotacao.setEnabled(true);
                    jLbEstatisticas.setEnabled(true);
                } else {
                    loginFrame.jLbErrorLb.setForeground(Color.red);
                    loginFrame.jTid.setText("");
                    loginFrame.jTpassword.setText("");
                    loginFrame.jTid.grabFocus();
                }
                break;
            case "CANCEL@PNLLoginFrame":
                System.exit(0);
                break;
        }
    }

    private void startVote() {
        new WNDVotacao().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContentPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(IMAGEM, this.getWidth()/2 - IMAGEM.getWidth(null)/2, this.getHeight()/2 - IMAGEM.getHeight(null)/2, this);
            }
        };
        ;
        jLabel1 = new javax.swing.JLabel();
        jLbConnection = new javax.swing.JLabel();
        jLbEleitores = new javax.swing.JLabel();
        jLbCandidatos = new javax.swing.JLabel();
        jLbVotacao = new javax.swing.JLabel();
        jLbEstatisticas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EX LEGE : SCP URN");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setFocusCycleRoot(false);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                onFocusGained(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jContentPanel.setBackground(new java.awt.Color(14, 56, 98));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Connection : ");

        jLbConnection.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLbConnection.setForeground(new java.awt.Color(254, 254, 254));
        jLbConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/exlege/view/gfx/connected.png"))); // NOI18N
        jLbConnection.setToolTipText("Connected!");

        jLbEleitores.setBackground(new java.awt.Color(254, 254, 254));
        jLbEleitores.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLbEleitores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/exlege/view/gfx/multiple-users-silhouette.png"))); // NOI18N
        jLbEleitores.setText("Eleitores");
        jLbEleitores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLbEleitores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbEleitores.setEnabled(false);
        jLbEleitores.setOpaque(true);
        jLbEleitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbEleitoresMouseClicked(evt);
            }
        });

        jLbCandidatos.setBackground(new java.awt.Color(254, 254, 254));
        jLbCandidatos.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLbCandidatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/exlege/view/gfx/political-candidate-speech.png"))); // NOI18N
        jLbCandidatos.setText("Candidatos");
        jLbCandidatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLbCandidatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbCandidatos.setEnabled(false);
        jLbCandidatos.setOpaque(true);
        jLbCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbCandidatosMouseClicked(evt);
            }
        });

        jLbVotacao.setBackground(new java.awt.Color(254, 254, 254));
        jLbVotacao.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLbVotacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/exlege/view/gfx/vote-badge-for-political-elections.png"))); // NOI18N
        jLbVotacao.setText("Votação");
        jLbVotacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLbVotacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbVotacao.setEnabled(false);
        jLbVotacao.setOpaque(true);
        jLbVotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbVotacaoMouseClicked(evt);
            }
        });

        jLbEstatisticas.setBackground(new java.awt.Color(254, 254, 254));
        jLbEstatisticas.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLbEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ru/exlege/view/gfx/increasing-data-graphic.png"))); // NOI18N
        jLbEstatisticas.setText("Estatísticas");
        jLbEstatisticas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLbEstatisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbEstatisticas.setEnabled(false);
        jLbEstatisticas.setOpaque(true);
        jLbEstatisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbEstatisticasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jContentPanelLayout = new javax.swing.GroupLayout(jContentPanel);
        jContentPanel.setLayout(jContentPanelLayout);
        jContentPanelLayout.setHorizontalGroup(
            jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jContentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbConnection))
                    .addComponent(jLbEstatisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbVotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbCandidatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbEleitores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jContentPanelLayout.setVerticalGroup(
            jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbConnection))
                .addGap(18, 18, 18)
                .addComponent(jLbEleitores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbCandidatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbVotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbEstatisticas)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jContentPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLbEleitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbEleitoresMouseClicked
        if (jLbEleitores.isEnabled()) {
            new WNDElectorKeep().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Opção desabilitada, insira suas informações.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLbEleitoresMouseClicked

    private void jLbCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbCandidatosMouseClicked
        if (jLbCandidatos.isEnabled()) {
            new WNDCandidateKeep().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Opção desabilitada, insira suas informações.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLbCandidatosMouseClicked

    private void jLbVotacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbVotacaoMouseClicked
        if (!PrivilegesDao.verifyDeadlock()) {
            if (jLbVotacao.isEnabled()) {
                int confirmation = JOptionPane.showConfirmDialog(null, "Deseja iniciar a votação?", "Votação", JOptionPane.OK_CANCEL_OPTION);
                if (confirmation == JOptionPane.OK_OPTION) {
                    boolean permissao = PrivilegesDao.verifyPrivileges(PasswordUtils.requestPassword("Inicio da votação", "Entre com a senha de administração : "));
                    if (permissao) {
                        startVote();
                    } else {
                        JOptionPane.showMessageDialog(null, "Permissão Negada.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Opção desabilitada, insira suas informações.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "A votação foi encerrada por um administrador", "Erro", JOptionPane.ERROR_MESSAGE);
            int confirmation = JOptionPane.showConfirmDialog(null, "Deseja dar continuidade a votação?", "Votação", JOptionPane.OK_CANCEL_OPTION);
            if (confirmation == JOptionPane.OK_OPTION) {
                boolean permissao = PrivilegesDao.verifyPrivileges(PasswordUtils.requestPassword("Inicio da votação", "Entre com a senha de administração : "));
                if (permissao) {
                    PrivilegesDao.revokeDeadlock();
                    startVote();
                } else {
                    JOptionPane.showMessageDialog(null, "Permissão Negada.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jLbVotacaoMouseClicked

    private void onFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_onFocusGained
        verifyConnection();
    }//GEN-LAST:event_onFocusGained

    private void jLbEstatisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbEstatisticasMouseClicked
        if (jLbEstatisticas.isEnabled()) {
            new WNDEstatisticas().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Opção desabilitada, insira suas informações.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLbEstatisticasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WNDMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WNDMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WNDMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WNDMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WNDMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jContentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbCandidatos;
    private javax.swing.JLabel jLbConnection;
    private javax.swing.JLabel jLbEleitores;
    private javax.swing.JLabel jLbEstatisticas;
    private javax.swing.JLabel jLbVotacao;
    // End of variables declaration//GEN-END:variables
}
